### ISSUE TITLE
Compilation did not complete

### ISSUE THREAD

**Issue by hshahin58** [lawik/lively#1]
Hi, I followed the instructions, but I got this error:
`Unchecked dependencies for environment dev:
* membrane_transcription (../membrane_transcription)
  the dependency is not available
** (Mix) Can't continue due to errors on dependencies`

**Comment by oleg-kiviljov** [comment]
Yes, can you add this one to the project please ? :)

**Comment by wstucco** [comment]
this should fix the issue

https://github.com/wstucco/lively/pull/1

**Comment by lawik** [comment]
Sorry about not noticing this issue earlier. My github notifications are poorly tuned.
Merged the PR. It should help.

I have been working with them as path deps since I edit both frequently during developing the talk. Consider wildly modifying membrane_transcription as well :D
